### ISSUE TITLE
Enable More ESLint Rulesets

### ISSUE THREAD

**Issue by AdrianAndersen** [webkom/lego#2036]
#### How to enable a ruleset:
1. Uncomment a ruleset from [.eslintrc.js](https://github.com/webkom/lego-webapp/blob/master/.eslintrc.js)
2. Run `yarn lint:js` to lint with the new rules
3. Fix the problems that occur
4. Ship it! :shipit: 

#### TODO:
- [ ] plugin:cypress/recommended
- [ ] plugin:jsx-a11y/recommended
- [ ] plugin:promise/recommended
- [ ] plugin:react-redux/recommended

**Comment by AdrianAndersen** [comment]
👀
